### ISSUE TITLE
ImageWizard.Azure does not work

### ISSUE THREAD

**Issue by OV2012** [usercode/ImageWizard#1]
Hi,
i have tested the untested "ImageWizard.Azure" package and it does net work :)

Setup:

> services.AddImageWizard(x =>
            {
                x.AllowUnsafeUrl = true;
                //x.Key = "DEMO-KEY---PLEASE-CHANGE-THIS-KEY---PLEASE-CHANGE-THIS-KEY---PLEASE-CHANGE-THIS-KEY---==";
            })
                .AddHttpLoader(x=>
                {
                    //x.RefreshMode = ImageLoaderRefreshMode.EveryTime;
                    x.SetHeader("Api", "XYZ");
                })
                .AddFileLoader()
                .AddYoutubeLoader()
                .AddGravatarLoader()
                .AddAnalytics()
                .AddAzureBlob(x =>
                {
                    x.ConnectionString = "UseDevelopmentStorage=true";
                    x.ContainerName = "test";
                });

and URL:
https://localhost:32768/image/unsafe/resize(500,500)/grayscale()/jpg(100)/azure/test.png

and result(in the browser): "image loader not found: azure"

it seems that imageLoader (see below) is alwas null .

`
Type imageLoaderType = ImageLoaderManager.Get(url_loaderType);
IImageLoader loader = (IImageLoader)context.RequestServices.GetService(imageLoaderType);
`

let me know if you need any further information
regards
Viktor

**Comment by usercode** [comment]
> i have tested the untested "ImageWizard.Azure" package and it does net work :)

Yeah, this can happen if you use untested packages. ;)

Now, this issue is fixed und tested with azure blob storage.

New nuget packages are also available.

Regards,
Christian

**Comment by OV2012** [comment]
Hi Christian,
thank you so much for the speedy fix! 
i can confirm it works now! :)
nice!
regards
Viktor
