### ISSUE TITLE
Get an error NETSDK1082 "There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'android-x64' or 'iossimulator-x64' or 'maccatalyst-x64'

### ISSUE THREAD

**Issue by SalvatoreDiFede** [usercode/ImageWizard#17]
**Describe the bug**

I get the error below when I reference ImageWizard.Client on **Maui** project:

NETSDK1082	There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'android-x64'.	Test.App (net8.0-android)	C:\Program Files\dotnet\sdk\8.0.303\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	491		

NETSDK1082	There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'iossimulator-x64'.	Test.App (net8.0-ios)	C:\Program Files\dotnet\sdk\8.0.303\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	491		

NETSDK1082	There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'maccatalyst-x64'.	Test.App (net8.0-maccatalyst)	C:\Program Files\dotnet\sdk\8.0.303\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	491	

**Steps To Reproduce**

1. Create a blank MAUI project
2. Reference ImageWizard.Client (via nuget or any other way)
3. Build project

**.NET Version**

8.0.303

**Comment by usercode** [comment]
Why do you want to use ImageWizard with a MAUI app?

ImageWizard.Client has dependencies on ASP.NET. It is usually only used server-side.
