### ISSUE TITLE
ambiguous reference (ResizeMode)

### ISSUE THREAD

**Issue by OV2012** [usercode/ImageWizard#2]
take a look at the picture  below:)
regards
viktor

![image](https://user-images.githubusercontent.com/1809404/81275178-984aa180-9051-11ea-80dc-165d3849e38c.png)

**Comment by usercode** [comment]
Ahhh, the shared project caused this issue. 

It's now fixed. 

Namepace "SharedContract" is renamed to "Utils".

I hope you read the readme. Since version 2.0 you have to add the imagesharp pipeline.
