### ISSUE TITLE
String parameter

### ISSUE THREAD

**Issue by haiduong87** [usercode/ImageWizard#3]
Hello @usercode 

Thanks for your great work.

I found a small problem with string parameter
https://github.com/usercode/ImageWizard/blob/master/src/ImageWizard.Core/ImageProcessing/ProcessingPipeline.cs#L99

We can change to

`ParameterItem p = CreateParameter(parameters[i], ".[^']+");`

Because 
""^func\('(?<param>.+)'\)$"
will match both
- hello('foo')
- hello('foo', 'bar')

Assume we have 2 overloads of hello
- hello(string p1)
- hello(string p1, string p2)

Regex test:
https://regexr.com/5fm3i

**Comment by haiduong87** [comment]
Also for floating number

https://github.com/usercode/ImageWizard/blob/f0cf90cade170fdda97cbf4fb732eae2a4345b32/src/ImageWizard.Core/ImageProcessing/ProcessingPipeline.cs#L91

The "\.\d+" part should be optional

Here's my proposal fix
`pp.Add(CreateParameter(currentParameter, @"-?\d+(\.\d+)?"));`

Note: I have a "-?\" to allow negative

**Comment by usercode** [comment]
Hi haiduong87,

thanks for using ImageWizard. :smiley:

I fixed the string pattern to "[^']*". This can handle empty strings, too.

Negative numbers are allowed, now.

For floating point numbers it's no good idea to add an optional part, because method overloading between integer and floating point numbers is not possible. 

Example:

```csharp
 [Filter]
 public void BackgroundColor(byte r, byte g, byte b)
 {
      Context.Image.Mutate(m => m.BackgroundColor(new Rgba32(r, g, b)));
 }

 [Filter]
 public void BackgroundColor(float r, float g, float b)
 {
     Context.Image.Mutate(m => m.BackgroundColor(new Rgba32(r, g, b)));
 }
```

**Comment by haiduong87** [comment]
Thanks for the explanation of the floating point 👍
