### ISSUE TITLE
Suggestion: improve regex for case of many parameters

### ISSUE THREAD

**Issue by haiduong87** [usercode/ImageWizard#4]
Hi usercode,

I'm trying to adapt this package (use the core, write my own plugin with skiasharp to match my requirements)
I found that with a filter that requires many parameters, it's a pain to fill all of them.

Example, I want to have a text filter (draw text watermark to an image), so I will have following overloads
- Text(string base64urlEncodedWatermark)
- Text(string base64urlEncodedWatermark, string base64urlEncodedFontName)
- Text(string base64urlEncodedWatermark, string base64urlEncodedFontName, float fontSize)
- ...

So I plan to update the middle ware to recognize the filter request as
- /text(text; 'helloworld', font: 'Comic Sans MS', fontSize: 72.0, color: '#00000')/
- Then I de serialized all parameters inside the '(' ')' pairs to an object/struct parameter
- Then call the private Text(TextWatermarkOptions option) function, which actually do the job.

Can you review my idea a bit.

I will implement and submit if it's okay.

haiduong87,
Thank you!

**Comment by usercode** [comment]
Ok, nice idea, because the string parameters can include URL-unfriendly chars. (Currently, if a string includes the char ")" the processing will throw an exception.)

Wait for the next commit, please. I think I can do it.

**Comment by haiduong87** [comment]
For best practice, I suggest all string parameters should be in base64urlencoded format.
When converting current code (gdi...) to use this on the fly processing, I have to deal with many url-unfriendly characters.
So I make the TextFilter to accept base64urlencoded format

**Comment by usercode** [comment]
I'm done. All string parameters can use Base64Url.

See this commit: https://github.com/usercode/ImageWizard/commit/c0ce6dbc39862ea6ee782091a91c6c4bfc458d14

**Comment by usercode** [comment]
What I don't did is combining all parameters to one. (I think it's nicer to see all parameters.)

You can create a pull request for that.

**Comment by haiduong87** [comment]
Ok, I will close this for now.
