### ISSUE TITLE
Net Standard 2.0

### ISSUE THREAD

**Issue by PrzemyslawKlys** [usercode/ImageWizard#6]
I wanted to try out ImageWizard and I noticed that in NuGet there's only the NET 5.0 version of DLL. Is it possible to get net standard 2.0? I'm asking because Net Standard 2.0 allows for higher compatibility with older Net Framework, yet allows you to use the library on Linux and macOS.

**Comment by usercode** [comment]
That's not possible, because ASP.NET isn't compatible anymore with .NET Standard.

Btw .NET 5.0 runs on Linux and macOS, too.

**Comment by PrzemyslawKlys** [comment]
I know, but I wanted to support PowerShell 5.1, so users with default net framework installation. .NET 5.0 requires a separate download. But I understand.
