### ISSUE TITLE
webp files partially loaded

### ISSUE THREAD

**Issue by labworkx** [usercode/ImageWizard#9]
Hi,

First of all thanks for this great library. I was looking for a way to dynamically load, resize and cache remote files and this is what I needed. 

While processing files I discovered some strange behavior. Webp files are not loaded correcty. There is no difference in loading it remote of from local files.  I tracked it down to the SkiaSharpPipline parsing the memory stream. 

https://github.com/usercode/ImageWizard/blob/111db369f2e63ba7f608070e5992c8d0f43cb5be/src/ImageWizard.SkiaSharp/SkiaSharpPipeline.cs#L56

I am not sure if this has to be fixed in ImageWizard or that this is something wrong in SkiaSharp.

When you first read the stream to a byte array and use the bytearray in SKBitmap.Decode it works as expected.

```
using MemoryStream ms = new MemoryStream();
context.Result.Data.CopyTo(ms);
var bytes = ms.ToArray();

SKBitmap bitmap = SKBitmap.Decode(bytes);

```
I don't know if this creates some new memory usage issues, but at least it is a workaround if you need it.

**Comment by usercode** [comment]
First, thanks for using ImageWizard! :smiley:

It seems that SkiaSharp cannot load images from http stream.

I fixed it like you proposed.

New docker image and nuget packages coming soon.
